[package]
name = "universal-heu-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["CHOSER Tech", "HITSZ OSA"]
license = "MIT"
description = "哈尔滨工程大学学位论文模板 | Harbin Engineering University"
repository = "https://github.com/soul667/universal-heu-thesis"
keywords = ["Harbin Engineering University", "thesis"]
categories = ["thesis"]
exclude = []
compiler = "0.13.0"

[template]
path = "templates"
entrypoint = "universal-bachelor.typ"
thumbnail = "thumbnail.png"
